import React from "react";
import DropMenu from "../DropMenu";
import "./TermsConditions.css";
import { Link } from "react-router-dom";

function TermsConditions({props}) {
  const {
    bwindi_Logo,
    spanText1,
    spanText2,
    spanText3,
    spanText4,
    spanText5,
    spanText6,
    spanText7,
    joinOurCommunity1,
    joinOurCommunity2,
    stayTunedForMore,
    yourEMail,
    subscribe,
    termsConditions,
    copyright,
    buy,
    about,
    jungle,
    roadmap,
    team,
    gallery,
    records,
    members,
    dropMenuProps,
  } = props;

  return (
    <div className="container-center-horizontal">
      


      <div className="terms-conditions-2 screen">
        <div className="flex-row-18" Style="margin: 0px auto;">
          <div className="flex-col-10">
              <img className="bwindi_logo-5" src={bwindi_Logo} alt=""/>
            {/* <div className="gallery-1 montserrat-bold-white-80px animate-enter15" show-on-scroll="true">
              <span className="montserrat-bold-kashmir-blue-80px">{spanText1}</span>
              <span className="montserrat-bold-saffron-80px">{spanText2}</span>
            </div> */}
          </div>
          <div className="flex-col-11">
            <div className="overlap-group2-2 jost-semi-bold-white-13px">
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/homepage#buybwindi">{buy}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/homepage">{about}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/homepage">{jungle}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/homepage">{roadmap}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/homepage">{team}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/gallery">{gallery}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/records">{records}</Link></div>
              <div className="overlap-group2-item-2 valign-text-middle"><Link to="/members">{members}</Link></div>
            </div>
            <DropMenu />
          </div>
        </div>



      
         
        <div className="terms-conditions-3 montserrat-bold-white-80px animate-enter12" show-on-scroll="true">
          <span className="montserrat-bold-kashmir-blue-80px" Style="  font-size: 60px;">{spanText1}</span>
          <span className="montserrat-bold-saffron-80px" Style="  font-size: 60px;">{spanText2}</span>
          <span className="span-3" Style="  font-size: 60px;">{spanText3}</span>
          <span className="span3" Style="  font-size: 60px;">{spanText4}</span>
          <span className="span-3" Style="  font-size: 60px;">{spanText5}</span>
          <span className="montserrat-bold-kashmir-blue-80px" Style="  font-size: 60px;">{spanText6}</span>
          <span className="montserrat-bold-saffron-80px" Style="  font-size: 60px;">{spanText7}</span>
        </div>
        <div className="flex-col-5">
          <div className="genral-the-bwindi-cl">
            GENRAL <br />
            <br />
            The Bwindi Club is a collection of digital artworks (NFTs) running on the Ethereum network. This website is
            an interface allowing participants to verify and exchange digital collectibles. Users are entirely
            responsible for the safety and management of their own private Ethereum wallets and validating all
            transactions and contracts generated by this website before approval. Furthermore, as the Bwindi Club smart
            contract runs on the Ethereum network, there is no liability or ability to undo, reverse, or restore any
            transactions.
            <br />
            <br />
            This website and its connected services are provided “as is” and “as available” without any kind of
            warranty. By using this website, you are accepting sole responsibility for all your transactions involving
            Bwindi Club digital collectibles.
            <br />
            <br />
            OWNERSHIP
            <br />
            <br />
            Each Bwindi the Adventurer is an NFT on the Ethereum blockchain. When you purchase an NFT using your
            Ethereum Wallet, you own the purchased Bwindi the Adventurer completely. Ownership of the NFT is mediated
            executed by the Smart Contract and the Ethereum and there is no reverse action to cancel the ownership after
            it is confirmed by the Ethereum network.
            <br />
            <br />
            PERSONAL USE
            <br />
            <br />
            After purchasing the Bwindi the Adventurer NFT, you become a member of the Bwindi Club and you must with
            these terms and any terms of use stated by the Bwindi Club. The ownership grants a worldwide, royalty-free
            license to use, copy, and display the purchased NFT, along with any extensions that the member chooses to
            create or use, within the limits of the following purposes: <br />
            1. member’s personal, non-commercial use; <br />
            2. as part of a marketplace that permits the purchase and sale of your Bwindi the Adventurer NFTs, provided
            that the marketplace cryptographically verifies each Bwindi the Adventurer NFT owner’s rights to display the
            artwork for their Bwindi the Adventurer NFT to ensure that only the actual owner can display the artwork; or{" "}
            <br />
            3. as part of a third-party website or application that permits the inclusion, involvement, or participation
            of your Bwindi the Adventurer NFT, provided that the website/application cryptographically verifies each
            Bwindi the Adventurer NFT owner’s rights to display the artwork for their Bwindi the Adventurer to ensure
            that only the actual owner can display the artwork, and provided that the artwork is no longer visible once
            the owner of the Bwindi the Adventurer leaves the website/application.
            <br />
            <br />
            COMMERCIAL USE
            <br />
            <br />
            After purchasing the Bwindi the Adventurer NFT, you become a member of the Bwindi Club and you must with
            these terms and any terms of use stated by the Bwindi Club. The ownership grants you an unlimited, worldwide
            license to use, copy, and display the purchased artwork for the purpose of creating derivative works based
            upon the artwork (“Commercial Use”). Examples of such Commercial Use would be the use of the artwork to
            produce and sell merchandise products displaying copies of the owned Bwindi the Adventurer.
          </div>
          <hr className="line9999"/>
          {/* <img className="line-9" src="/img/line-2@1x.svg" alt=""/> */}
          <div className="flex-row-7">
            <div className="join-our-community-container jost-bold-zircon-14px">
              <div className="join-our-community-2 valign-text-middle">{joinOurCommunity1}</div>
              <div className="join-our-community-2 valign-text-middle">{joinOurCommunity2}</div>
            </div>
            <p className="stay-tuned-for-more-2 valign-text-middle jost-semi-bold-white-15px">{stayTunedForMore}</p>
          </div>
          <div className="flex-row-8">
         
          <a target="blank" alt="twitter" href="https://twitter.com/Bwindi_NFTs"><img className="twitter" src="/img/twitter-1@2x.svg" alt=""/></a>
          <a target="blank" alt="linkedin" href="https://www.linkedin.com/company/bwindi/"><img className="flex-row-item" src="/img/linkedin-1@2x.svg" alt=""/></a>
          <a target="blank" alt="facebook" href="https://www.facebook.com/BwindiNFTs/"><img className="flex-row-item" src="/img/facebook-1@2x.svg" alt="" /></a>
          <a target="blank" alt="instagram" href="https://www.instagram.com/bwindi_nft/"><img className="flex-row-item" src="/img/instagram-1@2x.svg" alt=""/></a>
          <a target="blank" alt="discord" href="https://discord.com/invite/Swp4zj3Sqe"><img className="flex-row-item" src="/img/discord-1@2x.svg" alt=""/></a>
          <a target="blank" alt="youtube" href="https://www.youtube.com/channel/UCOqVypNUxB7G_18AOXQ_1pg"><img className="flex-row-item" src="/img/youtube@2x.svg" alt=""/></a>
       
            <div className="mail-container-2 border-1px-gray-chateau">
              <img className="mail-2" src="/img/mail-1@2x.svg" alt=""/>
              <div className="your-e-mail-2 valign-text-middle jost-normal-gray-chateau-14px">{yourEMail}</div>
            </div>
            <div className="subscribe-3">
              <div className="subscribe-4 valign-text-middle jost-medium-black-14px">{subscribe}</div>
            </div>
          </div>
          <div className="flex-row-9 jost-bold-white-14px">
            <div className="terms-conditions-4 valign-text-middle"><Link to="/terms-conditions">{termsConditions}</Link></div>
            <p className="copyright-2 valign-text-middle"><a target="blank" href="https://bwindi.io/">{copyright}</a></p>
          </div>
        </div>
      </div> 
    </div>
  );
}

export default TermsConditions;
